### ISSUE TITLE
Wrong filename

### ISSUE THREAD

**Issue by woctezuma** [IGLICT/DeepFaceEditing-Jittor#2]
https://github.com/IGLICT/DeepFaceEditing-Jittor/blob/32b7bce2c60679523e27ca73d8e165418b57fb77/combine_model.py#L43

```
load the weight of global fuse
Traceback (most recent call last):
  File "test_model.py", line 55, in <module>
    model.initialize()
  File "/content/DeepFaceEditing-Jittor/combine_model.py", line 43, in initialize
    self.netG.load('./checkpoints/global_fuse_25.pkl')
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 997, in load
    self.load_parameters(load(path))
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 698, in load
    model_dict = safeunpickle(path)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 73, in safeunpickle
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/global_fuse_25.pkl'
```

![checkpoints](https://i.imgur.com/jkrvrpQ.png)

**Comment by onlineplay** [comment]
Sorry, we changed the file name, it's missing here. 
Now it's fixed, you can update it or delete '_25'. 
Thanks very much for your issue.
